name: Build Project
on:
  push:
    branches: [main]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:
env:
  NUGET_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  GITHUB_PACKAGE_USER_NAME: ${{ github.repository_owner }}
  GITHUB_PACKAGE_TOKEN: ${{ secrets.EXTERNAL_PAT }}
jobs:
  build:
    #if: ! github.event.pull_request.draft
    runs-on: ubuntu-latest
    permissions:
      contents: write # for checkout and tag
      pull-requests: write  # for comments
      packages: write # for publish
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/runenilsenoe/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: dotnet tool Install
        run: dotnet tool restore
      - name: Build solution 
        working-directory: ConsoleApp1
        run: |
          dotnet build ConsoleApp1.sln 
